name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    # ... (追加のステップ)

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory/aws_ec2.yml ansible/playbooks/hello_world.yml
    # ... (追加のステップ)
